cpuids:
  0: 
    name: "Start"
    data_type:
      type: Start

  1:
    name: "Model"
    data_type:
      type: BitField
      eax:
        - type: Int
          name: stepping
          bounds:
            start: 0
            end: 4
        - type: Int
          name: model
          bounds:
            start: 4
            end: 8
        - type: Int
          name: family
          bounds:
            start: 8
            end: 11
      ebx: []
      ecx:
        - type: Flag
          name: SSE3
          bit: 0
        - type: Flag
          name: VMX
          bit: 5

      edx:
        - type: Flag
          name: fpu
          bit: 0
        - type: Flag
          name: vme
          bit: 0

  0x40000000:
    name: "Hypervisor ID"
    data_type:
      type: Start
  
  0x40000001:
    name: "Hypervisor Vendor-Neutral ID"
    data_type:
      type: String

  0x40000002:
    name: "Hypervisor System ID"
    data_type:
      type: BitField
      eax: 
        - {type: Int, name: "Build Number", bounds: {start: 0, end: 31}}
      ebx: 
        - {type: Int, name: "Major", bounds: {start: 16, end: 31}}
        - {type: Int, name: "Minor", bounds: {start: 0, end: 15}}
      ecx: []
      edx: []

  0x40000003:
    name: "Hypervisor Feature ID"
    data_type:
      type: BitField
      eax: 
        - {type: Int, name: "Privilege Mask Low", bounds: {start: 0, end: 31}}
      ebx: 
        - {type: Int, name: "Privilege Mask High", bounds: {start: 0, end: 31}}
      ecx: 
        - {type: Flag, name: Mperf, bit: 5}
        - {type: Flag, name: "Shadow Stack", bit: 6}
        - {type: Flag, name: PMU, bit: 7}
        - {type: Flag, name: "Trap Intercept", bit: 8}
      edx:
        - {type: Flag, name: MWAIT(Depricated), bit: 0}
        - {type: Flag, name: Debug, bit: 1}
        - {type: Flag, name: PerfMon, bit: 2}
        - {type: Flag, name: "Physical partition events", bit: 3}
        - {type: Flag, name: Hypercall XMM, bit: 4}
        - {type: Flag, name: Guest Idle, bit: 5}
        - {type: Flag, name: Hypervisor sleep, bit: 6}
        - {type: Flag, name: NUMA, bit: 7}
        - {type: Flag, name: Timer Freq., bit: 8}
        - {type: Flag, name: MCEInject, bit: 9}
        - {type: Flag, name: Crash MSR, bit: 10}
        - {type: Flag, name: Debug MSR, bit: 11}
        - {type: Flag, name: NPIEP, bit: 12}
        - {type: Flag, name: DisableHypervisorAvailable, bit: 13}
        - {type: Flag, name: ExtendedGvaRangesForFlushVirtualAddressListAvailable, bit: 14}
        - {type: Flag, name: Hypercall XMM Return, bit: 15}
        - {type: Flag, name: SintPollingModeAvailable, bit: 17}
        - {type: Flag, name: HypercallMsrLockAvailable, bit: 18}
        - {type: Flag, name: Direct Synthetic Timers, bit: 19}
        - {type: Flag, name: PAT VSM, bit: 20}
        - {type: Flag, name: bindcfgs VSM, bit: 21}
        - {type: Flag, name: Unhalted Timer, bit: 23}
        - {type: Flag, name: LBR, bit: 26}

  0x40000005:
    name: "Hypervisor Feature ID"
    data_type:
      type: BitField
      eax: 
        - {type: Int, name: "Max Virtual Porcessors", bounds: {start: 0, end: 31}}
      ebx: 
        - {type: Int, name: "Max Logical Porcessors", bounds: {start: 0, end: 31}}
      ecx:
        - {type: Int, name: "Max Pysical Interrupt Vectors", bounds: {start: 0, end: 31}}
      edx: []

  0x80000002:
    name: "Brand String 1"
    data_type:
      type: String

  0x80000003:
    name: "Brand String 2"
    data_type:
      type: String

  0x80000004:
    name: "Brand String 3"
    data_type:
      type: String
msrs:
  - name: Arch Capabilities
    address: 0x10a
    fields:
      - {type: Flag, name: "Rogue Data Cache Load", bit: 0}
      - {type: Flag, name: "Enhanced IBRS", bit: 1}
      - type: Flag
        name: MDS_NO
        bit: 5
      - type: Flag
        name: TAA_NO
        bit: 8
      - {type: Flag, name: "TSX_CTRL", bit: 7}
  - name: Basic VMX
    address: 0x480
    fields:
      - {type: Int, name: "Revision", bounds:{ start: 0, end: 30}}
      - {type: Int, name: "VMXON size", bounds: { start: 32, end: 44}}
      - {type: Flag, name: "VMX controls", bit: 55}
      - {type: Flag, name: "Soft exceptions", bit: 56}
  - name: "VMX: Pin-based Ctls"
    address: 0x481
    fields:
      - {type: Flag, name: "Ext Int Exit", bit: 32}
      - {type: Flag, name: "NMI Exits", bit: 35}
      - {type: Flag, name: "Virt NMI", bit: 37}
      - {type: Flag, name: "VMX Timer", bit: 38}
      - {type: Flag, name: "posted Int", bit: 39}

  - name: "VMX: True Pin-based Ctls"
    address: 0x48D
    fields:
      - {type: Flag, name: "Ext Int Exit", bit: 32}
      - {type: Flag, name: "NMI Exits", bit: 35}
      - {type: Flag, name: "Virt NMI", bit: 37}
      - {type: Flag, name: "VMX Timer", bit: 38}
      - {type: Flag, name: "posted Int", bit: 39}

  - name: "VMX: Proccessor Based Ctls - Most"
    address: 0x482
    fields:
      - {type: Flag, name: "Int Window Exit", bit: 34}
      - {type: Flag, name: "TSC Offsetting", bit: 35}
      - {type: Flag, name: "HLT exit", bit: 39}
      - {type: Flag, name: "INVLPG exit", bit: 41}
      - {type: Flag, name: "MWAIT exit", bit: 42}
      - {type: Flag, name: "RDPMC exit", bit: 43}
      - {type: Flag, name: "RDTSC exit", bit: 44}
      - {type: Flag, name: "Ctls 3", bit: 49 }
      - {type: Flag, name: "Ctls 2", bit: 63}

  - name: "VMX: Proccessor Based Ctls - All"
    address: 0x48E
    fields: []

  - name: "VMX: Proccessor Based Ctls 2"
    address: 0x48B
    fields:
      - {type: Flag, name: "Virt APIC", bit: 32}
      - {type: Flag, name: "TSC scaling", bit: 57}

  - name: "VMX: Proccessor Based Ctls 3"
    address: 0x492
    fields: []
