cpuids:
  0: 
    name: "Start"
    data_type:
      type: Start

  1:
    name: "Model"
    data_type:
      type: BitField
      eax:
        - type: Int
          name: stepping
          bounds:
            start: 0
            end: 4
        - type: X86Model
          name: model
        - type: X86Family
          name: family
          bounds:
            start: 8
            end: 11
      ebx: []
      ecx:
        - type: Flag
          name: SSE3
          bit: 0
        - type: Flag
          name: VMX
          bit: 5
        - {type: Flag, name: AESNI, bit: 25}

      edx:
        - type: Flag
          name: fpu
          bit: 0
        - type: Flag
          name: vme
          bit: 0

  0x00000007:
    name: "Structured Extened Flags"
    data_type:
      type: SubLeafBitField
      leaves:
        - eax:
          - {type: Int, name: "Sub-Leaf Count", bounds: {start: 0, end: 31}}
          ebx:
          - {type: Flag, name: HLE, bit: 4}
          - {type: Flag, name: RTM, bit: 11}
          - {type: Flag, name: MPX, bit: 14}
          - {type: Flag, name: PT, bit: 25}
          ecx: []
          edx:
          - {type: Flag, name: "AVX512 VP2Intersect", bit: 8}
          - {type: Flag, name: "RTM Always Abort", bit: 11}
          - {type: Flag, name: "RTM Force Abort", bit: 13}
          - {type: Flag, name: "Arch_Capabilities", bit: 29}
          - {type: Flag, name: "Core_Capabilities", bit: 30}
        - eax:
          - {type: Flag, name: "AVX VNNI", bit: 14}
          ebx: []
          ecx: []
          edx: []
        - eax: []
          ebx: []
          ecx: []
          edx:
          - {type: Flag, name: PSFD, bit: 0}

  0x40000000:
    name: "Hypervisor ID"
    data_type:
      type: Start
  
  0x40000001:
    name: "Hypervisor Vendor-Neutral ID"
    data_type:
      type: String

  0x40000002:
    name: "Hypervisor System ID"
    data_type:
      type: BitField
      eax: 
        - {type: Int, name: "Build Number", bounds: {start: 0, end: 31}}
      ebx: 
        - {type: Int, name: "Major", bounds: {start: 16, end: 31}}
        - {type: Int, name: "Minor", bounds: {start: 0, end: 15}}
      ecx: []
      edx: []

  0x40000003:
    name: "Hypervisor Feature ID"
    data_type:
      type: BitField
      eax: 
        - {type: Int, name: "Privilege Mask Low", bounds: {start: 0, end: 31}}
      ebx: 
        - {type: Int, name: "Privilege Mask High", bounds: {start: 0, end: 31}}
      ecx: 
        - {type: Flag, name: Mperf, bit: 5}
        - {type: Flag, name: "Shadow Stack", bit: 6}
        - {type: Flag, name: PMU, bit: 7}
        - {type: Flag, name: "Trap Intercept", bit: 8}
      edx:
        - {type: Flag, name: MWAIT(Depricated), bit: 0}
        - {type: Flag, name: Debug, bit: 1}
        - {type: Flag, name: PerfMon, bit: 2}
        - {type: Flag, name: "Physical partition events", bit: 3}
        - {type: Flag, name: Hypercall XMM, bit: 4}
        - {type: Flag, name: Guest Idle, bit: 5}
        - {type: Flag, name: Hypervisor sleep, bit: 6}
        - {type: Flag, name: NUMA, bit: 7}
        - {type: Flag, name: Timer Freq., bit: 8}
        - {type: Flag, name: MCEInject, bit: 9}
        - {type: Flag, name: Crash MSR, bit: 10}
        - {type: Flag, name: Debug MSR, bit: 11}
        - {type: Flag, name: NPIEP, bit: 12}
        - {type: Flag, name: DisableHypervisorAvailable, bit: 13}
        - {type: Flag, name: ExtendedGvaRangesForFlushVirtualAddressListAvailable, bit: 14}
        - {type: Flag, name: Hypercall XMM Return, bit: 15}
        - {type: Flag, name: SintPollingModeAvailable, bit: 17}
        - {type: Flag, name: HypercallMsrLockAvailable, bit: 18}
        - {type: Flag, name: Direct Synthetic Timers, bit: 19}
        - {type: Flag, name: PAT VSM, bit: 20}
        - {type: Flag, name: bindcfgs VSM, bit: 21}
        - {type: Flag, name: Unhalted Timer, bit: 23}
        - {type: Flag, name: LBR, bit: 26}

  0x40000005:
    name: "Hypervisor Feature ID"
    data_type:
      type: BitField
      eax: 
        - {type: Int, name: "Max Virtual Porcessors", bounds: {start: 0, end: 31}}
      ebx: 
        - {type: Int, name: "Max Logical Porcessors", bounds: {start: 0, end: 31}}
      ecx:
        - {type: Int, name: "Max Pysical Interrupt Vectors", bounds: {start: 0, end: 31}}
      edx: []

  0x80000002:
    name: "Brand String 1"
    data_type:
      type: String

  0x80000003:
    name: "Brand String 2"
    data_type:
      type: String

  0x80000004:
    name: "Brand String 3"
    data_type:
      type: String
msrs:
  - name: "Core_Capabilities"
    address: 0xCF
    fields:
      - {type: Flag, name: "SPLIT_LOCK_DISABLE_SUPPORTED", bit: 5}

  - name: Arch Capabilities
    address: 0x10a
    fields:
      - {type: Flag, name: RDCL_NO, bit: 0}
      - {type: Flag, name: IBRS_ALL, bit: 1}
      - {type: Flag, name: RSBA, bit: 2}
      - {type: Flag, name: SKIP_L1DF_VMENTRY, bit: 3}
      - {type: Flag, name: SSB_NO, bit: 4}
      - {type: Flag, name: MDS_NO, bit: 5}
      - {type: Flag, name: IF_PSCHANGE_MC_NO, bit: 6}
      - {type: Flag, name: TSX_CTRL, bit: 7}
      - {type: Flag, name: TAA_NO, bit: 8}
      - {type: Flag, name: GDS_CTRL, bit: 25}
      - {type: Flag, name: GDS_NO, bit: 26}
  - name: Microcode Update Option Control
    address: 0x123
    fields:
      - {type: Flag, name: "GDS_MITG_DIS", bit: 4}
      - {type: Flag, name: "GDS_MITG_LOCK", bit: 5}
  - name: "Perf_Capabilities"
    address: 0x345
    fields:
      - {type: Int, name: "LBR_FMT", bounds: {start: 0, end: 5}}
      - {type: Flag, name: "PEBSTrap", bit: 6}
      - {type: Flag, name: "PEBSArchRegs", bit: 7}
      - {type: Int, name: "PEBS_FMT",bounds: {start: 8, end: 11}}
      - {type: Flag, name: "SMM_FREEZE", bit: 12}
      - {type: Flag, name: "FULL_WRITE", bit: 13}
      - {type: Flag, name: "PEBS_BASELINE", bit: 14}
      - {type: Flag, name: "METRICS_AVAIL", bit: 15}
      - {type: Flag, name: "PEBS_PT_AVAIL", bit: 16}
  - name: Basic VMX
    address: 0x480
    fields:
      - {type: Int, name: "Revision", bounds:{ start: 0, end: 30}}
      - {type: Int, name: "VMXON size", bounds: { start: 32, end: 44}}
      - {type: Flag, name: "VMX controls", bit: 55}
      - {type: Flag, name: "Soft exceptions", bit: 56}
  - name: "VMX: Pin-based Ctls"
    address: 0x481
    fields:
      - {type: Flag, name: "Ext Int Exit", bit: 32}
      - {type: Flag, name: "NMI Exits", bit: 35}
      - {type: Flag, name: "Virt NMI", bit: 37}
      - {type: Flag, name: "VMX Timer", bit: 38}
      - {type: Flag, name: "posted Int", bit: 39}

  - name: "VMX: True Pin-based Ctls"
    address: 0x48D
    fields:
      - {type: Flag, name: "Ext Int Exit", bit: 32}
      - {type: Flag, name: "NMI Exits", bit: 35}
      - {type: Flag, name: "Virt NMI", bit: 37}
      - {type: Flag, name: "VMX Timer", bit: 38}
      - {type: Flag, name: "posted Int", bit: 39}

  - name: "VMX: Proccessor Based Ctls - Most"
    address: 0x482
    fields: 
      - {type: Flag, name: "Int Window Exit", bit: 34}
      - {type: Flag, name: "TSC Offsetting", bit: 35}
      - {type: Flag, name: "HLT exit", bit: 39}
      - {type: Flag, name: "INVLPG exit", bit: 41}
      - {type: Flag, name: "MWAIT exit", bit: 42}
      - {type: Flag, name: "RDPMC exit", bit: 43}
      - {type: Flag, name: "RDTSC exit", bit: 44}
      - {type: Flag, name: "CR3-load exit", bit: 47}
      - {type: Flag, name: "CR3-store exit", bit: 48}
      - {type: Flag, name: "Ctls 3", bit: 49 }
      - {type: Flag, name: "CR8-load exit", bit: 51}
      - {type: Flag, name: "CR8-store exit", bit: 52}
      - {type: Flag, name: "TPR Shadow", bit: 53}
      - {type: Flag, name: "NMI exit", bit: 54}
      - {type: Flag, name: "MOV-DR exit", bit: 55}
      - {type: Flag, name: "IO exit-all", bit: 56}
      - {type: Flag, name: "IO bitmap", bit: 57}
      - {type: Flag, name: "Monitor Trap", bit: 59}
      - {type: Flag, name: "MSR bitmap", bit: 60}
      - {type: Flag, name: "MONITOR exit", bit: 61}
      - {type: Flag, name: "PAUSE exit", bit: 62}
      - {type: Flag, name: "Ctls 2", bit: 63}

  - name: "VMX: Proccessor Based Ctls - All"
    address: 0x48E
    fields: 
      - {type: Flag, name: "Int Window Exit", bit: 34}
      - {type: Flag, name: "TSC Offsetting", bit: 35}
      - {type: Flag, name: "HLT exit", bit: 39}
      - {type: Flag, name: "INVLPG exit", bit: 41}
      - {type: Flag, name: "MWAIT exit", bit: 42}
      - {type: Flag, name: "RDPMC exit", bit: 43}
      - {type: Flag, name: "RDTSC exit", bit: 44}
      - {type: Flag, name: "CR3-load exit", bit: 47}
      - {type: Flag, name: "CR3-store exit", bit: 48}
      - {type: Flag, name: "Ctls 3", bit: 49 }
      - {type: Flag, name: "CR8-load exit", bit: 51}
      - {type: Flag, name: "CR8-store exit", bit: 52}
      - {type: Flag, name: "TPR Shadow", bit: 53}
      - {type: Flag, name: "NMI exit", bit: 54}
      - {type: Flag, name: "MOV-DR exit", bit: 55}
      - {type: Flag, name: "IO exit-all", bit: 56}
      - {type: Flag, name: "IO bitmap", bit: 57}
      - {type: Flag, name: "Monitor Trap", bit: 59}
      - {type: Flag, name: "MSR bitmap", bit: 60}
      - {type: Flag, name: "MONITOR exit", bit: 61}
      - {type: Flag, name: "PAUSE exit", bit: 62}
      - {type: Flag, name: "Ctls 2", bit: 63}

  - name: "VMX: Proccessor Based Ctls 2"
    address: 0x48B
    fields:
      - {type: Flag, name: "Virt APIC", bit: 32}
      - {type: Flag, name: "Enable EPT", bit: 33}
      - {type: Flag, name: "Descriptor Table exit", bit: 34}
      - {type: Flag, name: "Enable RDTSCP", bit: 35}
      - {type: Flag, name: "Virt x2APIC", bit: 36}
      - {type: Flag, name: "Enable VPID", bit: 37}
      - {type: Flag, name: "WBINVD exit", bit: 38}
      - {type: Flag, name: "unrestricted", bit: 39}
      - {type: Flag, name: "Virt Apic", bit: 40}
      - {type: Flag, name: "Virt Interrupts", bit: 41}
      - {type: Flag, name: "PAUSE loop exit", bit: 42}
      - {type: Flag, name: "RDRAND exit", bit: 43}
      - {type: Flag, name: "Enable INVPCID", bit: 44}
      - {type: Flag, name: "Enable VMFUNC", bit: 45}
      - {type: Flag, name: "VMCS shadow", bit: 46}
      - {type: Flag, name: "ENCLS exit", bit: 47}
      - {type: Flag, name: "RDSEED exit", bit: 48}
      - {type: Flag, name: "Enable PML", bit: 49}
      - {type: Flag, name: "EPT exceptions", bit: 50}
      - {type: Flag, name: "VMX-PT conceal", bit: 51}
      - {type: Flag, name: "Enable XSAVE", bit: 52}
      - {type: Flag, name: "Mode EPT Ctrl", bit: 54}
      - {type: Flag, name: "EPT Write Perm size", bit: 55}
      - {type: Flag, name: "PT - Guest Addr", bit: 56}
      - {type: Flag, name: "TSC scaling", bit: 57}
      - {type: Flag, name: "User Wait", bit: 58}
      - {type: Flag, name: "Enable Pconfig", bit: 59}
      - {type: Flag, name: "ENCLV Exit", bit: 60}

  - name: "VMX: Proccessor Based Ctls 3"
    address: 0x492
    fields:
      - {type: Flag, name: "LOADIWKEY", bit: 0}
      - {type: Flag, name: "Enable HLAT", bit: 1}
      - {type: Flag, name: "EPT Write Ctrl", bit: 2}
      - {type: Flag, name: "Guest Page Verify", bit: 3}
